### ISSUE TITLE
Relax version requirement for rack

### ISSUE THREAD

**Issue by fschwahn** [benzado/heroic-sns#11]
I'm trying to use this with rails 5, and it's not working because rails5 depends on rack 2.x. If you could relax the requirement to `>= 1.4`, that would solve this problem.

**Comment by benzado** [comment]
@fschwahn Where can I go to find out what's changed in Rack 2.x? It doesn't seem like http://rack.github.io is being updated.

**Comment by fschwahn** [comment]
@benzado I have no idea to be honest - I think the best information currently available can be found here: https://github.com/rack/rack/blob/2.0.0.alpha/HISTORY.md However, after briefly looking I don't even know what's the breaking change which warrants the major bump.

That said, `heroic-sns` seems to work flawlessly.

**Comment by fschwahn** [comment]
Rack 2 final has been released, but there's still no easy way to see what changed. There is no now an issue tracking this problem (https://github.com/rack/rack/issues/1092), but for now the only way to know is looking at the diff between 1.6.4 and 2.0.1 .

**Comment by benzado** [comment]
@fschwahn Can you submit a pull request to relax the version requirement and also bump the gem version to 1.1.3?

**Comment by fschwahn** [comment]
see #12
