### ISSUE TITLE
Punchlist for 1.2

### ISSUE THREAD

**Issue by benzado** [benzado/heroic-sns#18]
- Drop support for Ruby < 2.0 (Travis doesn't seem to support it anyway)
- Add 2.4+ to travis.yml
- Does this mean we drop Rack 1.x support?
- Merge #15 for stricter cert check
- Add #14 relaxed JSON dependency to release notes
- Merge #13 for better error message
- review forks for anything worthwhile
- update rake
- update release notes, etc.

**Comment by benzado** [comment]
Hey @andreas-venturini and @fschwahn I've _finally_ prepared a 1.2 release on the master branch. Are either of you interested in testing or reviewing before I push a release to rubygems? All the unit tests are passing [here](https://travis-ci.org/github/benzado/heroic-sns); beyond that, I don't have any active apps using the gem that I could perform further testing with.

**Comment by andreas-venturini** [comment]
@benzado I could point the latest master to one of our staging apps to check - however, reviewing the changes since the last release they LGTM - nothing "major" that I would be afraid of pushing to prod.

Just one question: Why did you revert dropping support for Ruby 1.8 and 1.9?

**Comment by benzado** [comment]
> I could point the latest master to one of our staging apps to check - however, reviewing the changes since the last release they LGTM - nothing "major" that I would be afraid of pushing to prod.

Sounds good to me, then. I'll push it out later today.

> Just one question: Why did you revert dropping support for Ruby 1.8 and 1.9?

I only dropped them because I thought I couldn't continue testing them on Travis CI, and I couldn't install 1.8.7 locally. Then I discovered a workaround (specify the Linux version to test on), so I figured why not put it back if I can?

**Comment by benzado** [comment]
Released! https://rubygems.org/gems/heroic-sns/versions/1.2
