### ISSUE TITLE
Warn if payload size is too large?

### ISSUE THREAD

**Issue by benzado** [benzado/heroic-sns#5]
Amazon allows payloads of up to 256KB. Should we reject incoming messages that are over the limit?

**Comment by cobbr2** [comment]
Don't know if you're still maintaining this, but my opinion would be 'no'. The signature work is already doing the work of authenticating the message, and AWS could change the allowed payload size with the stroke of a pen.

**Comment by benzado** [comment]
> Don't know if you're still maintaining this ...

I think I am... it hasn't seen much activity lately but I'm assuming that's because it is working OK. `:-)`

> but my opinion would be 'no'. The signature work is already doing the work of authenticating the message, and AWS could change the allowed payload size with the stroke of a pen.

Good point! When I entered this issue I think I had a mindset of following the spec obsessively.
